__Exercício 4: Ruído e Filtragem Digital__

In [1]:
#=====================================================
#  1. Leitura e visualização dos dados
#====================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#=======================================================
#  Visualização dos dados experimentais simulados
#=======================================================
tabela = pd.read_csv("sensor_ruidoso.csv")
tabela

   tempo_s  sensor_ruidoso_C  sensor_referencia_C
0        0              25.5                 25.0
1        1              26.2                 25.1
2        2              24.8                 25.0
3        3              27.0                 25.0
4        4              23.9                 25.0
5        5              26.8                 25.0
6        6              24.5                 25.0
7        7              27.2                 25.0
8        8              23.8                 25.0
9        9              26.5                 25.0

In [3]:
#==========================================================
# 2. Cálculo do ruído
#==========================================================

tabela["ruido_C"] = (
    tabela["sensor_ruidoso_C"] - 
    tabela["sensor_referencia_C"]
    )

tabela

   tempo_s  sensor_ruidoso_C  sensor_referencia_C  ruido_C
0        0              25.5                 25.0      0.5
1        1              26.2                 25.1      1.1
2        2              24.8                 25.0     -0.2
3        3              27.0                 25.0      2.0
4        4              23.9                 25.0     -1.1
5        5              26.8                 25.0      1.8
6        6              24.5                 25.0     -0.5
7        7              27.2                 25.0      2.2
8        8              23.8                 25.0     -1.2
9        9              26.5                 25.0      1.5

In [4]:
#========================================================
# 3. Caracterização quantitativa do sinal original 
#========================================================

# Média do ruído
ruido_medio = tabela["ruido_C"].mean()

# Desvio padrão amostral do ruído
desvio_ruido = tabela["ruido_C"].std()

# Erro absoluto em cada ponto de medição
tabela["erro_original_C"] = np.abs(
    tabela["ruido_C"]
    )

# Erro absoluto médio
erro_original_medio = tabela["erro_original_C"].mean()

# Apresentação dos resultaldos
print("-----------------------------------------------")
print("Caracterização do sinal original")
print("-----------------------------------------------")
print(f"Ruído médio = {ruido_medio:.4f} °C")
print(f"Desvio padrão do ruído = {desvio_ruido:.4f} °C")
print(f"Erro absoluto médio = {erro_original_medio:.4f} °C")
print("------------------------------------------------")

-----------------------------------------------
Caracterização do sinal original
-----------------------------------------------
Ruído médio = 0.6100 °C
Desvio padrão do ruído = 1.2914 °C
Erro absoluto médio = 1.2100 °C
------------------------------------------------

In [5]:
tabela

   tempo_s  sensor_ruidoso_C  sensor_referencia_C  ruido_C  erro_original_C
0        0              25.5                 25.0      0.5              0.5
1        1              26.2                 25.1      1.1              1.1
2        2              24.8                 25.0     -0.2              0.2
3        3              27.0                 25.0      2.0              2.0
4        4              23.9                 25.0     -1.1              1.1
5        5              26.8                 25.0      1.8              1.8
6        6              24.5                 25.0     -0.5              0.5
7        7              27.2                 25.0      2.2              2.2
8        8              23.8                 25.0     -1.2              1.2
9        9              26.5                 25.0      1.5              1.5

In [ ]:
#=============================================================
# 4. Aplicação do filtro de média móvel
#=============================================================

# Número da média móvel
tabela["media_movel_C"] = (
    tabela["sensor_ruidoso_C"].rolling(window=N, min_periods=1)
    .mean()
)

# Visualização dos resultados
print(
    tabela[
        [
            "tempo_ruidoso_C",
            "sensor_referencia_C",
            "media_movel_C"
        ]
    ]
)